"""add translations table

Revision ID: 57c6b0ea13f8
Revises: 
Create Date: 2025-12-24 22:54:29.988202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57c6b0ea13f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.String(length=255), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_language', sa.String(length=10), nullable=False),
    sa.Column('target_language', sa.String(length=10), nullable=False),
    sa.Column('original_content', sa.Text(), nullable=False),
    sa.Column('translated_content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'content_hash', 'target_language', name='uq_chapter_hash_language')
    )
    op.create_index('idx_translations_lookup', 'translations', ['chapter_id', 'content_hash', 'target_language'], unique=False)
    op.create_index(op.f('ix_translations_chapter_id'), 'translations', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_translations_content_hash'), 'translations', ['content_hash'], unique=False)
    op.create_index(op.f('ix_translations_target_language'), 'translations', ['target_language'], unique=False)
    op.create_index(op.f('ix_translations_user_id'), 'translations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translations_user_id'), table_name='translations')
    op.drop_index(op.f('ix_translations_target_language'), table_name='translations')
    op.drop_index(op.f('ix_translations_content_hash'), table_name='translations')
    op.drop_index(op.f('ix_translations_chapter_id'), table_name='translations')
    op.drop_index('idx_translations_lookup', table_name='translations')
    op.drop_table('translations')
    # ### end Alembic commands ###
