"""add translation_feedback table

Revision ID: 809b34b1c5dc
Revises: 57c6b0ea13f8
Create Date: 2025-12-25 01:42:15.691192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '809b34b1c5dc'
down_revision: Union[str, None] = '57c6b0ea13f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('translation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('issue_description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['translation_id'], ['translations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_feedback_translation_id'), 'translation_feedback', ['translation_id'], unique=False)
    op.create_index(op.f('ix_translation_feedback_user_id'), 'translation_feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translation_feedback_user_id'), table_name='translation_feedback')
    op.drop_index(op.f('ix_translation_feedback_translation_id'), table_name='translation_feedback')
    op.drop_table('translation_feedback')
    # ### end Alembic commands ###
